const events = [
 {title:'Boston Lights: A Lantern Experience',date:'2026-09-21',end:'2026-11-08',region:'Greater Boston',city:'Boston',venue:'Franklin Park Zoo',category:'Family',free:false,featured:true,source:'https://www.meetboston.com/'},
 {title:"Let’s Dance Boston",date:'2026-09-23',end:'2026-09-27',region:'Greater Boston',city:'Boston',venue:'Downtown Boston',category:'Arts & Culture',free:true,featured:true,source:'https://www.meetboston.com/'},
 {title:'Wicked',date:'2026-09-23',end:'2026-11-15',region:'Greater Boston',city:'Boston',venue:'Citizens Opera House',category:'Arts & Culture',free:false,featured:true,source:'https://www.meetboston.com/'},
 {title:'Cape Ann Plein Air',date:'2026-10-03',end:'2026-10-11',region:'North Shore',city:'Essex / Cape Ann',venue:'Cape Ann',category:'Arts & Culture',free:false,featured:true,source:'https://www.visitma.com/events/'},
 {title:'29th Annual MANHATTAN SHORT Film Festival',date:'2026-09-24',region:'South Shore + South Coast',city:'New Bedford',venue:'New Bedford',category:'Arts & Culture',free:false,featured:false,source:'https://www.visitma.com/events/'},
 {title:'Cranberries & Cocktails',date:'2026-09-25',region:'South Shore + South Coast',city:'Middleborough',venue:'Middleborough',category:'Food & Drink',free:false,featured:true,source:'https://www.visitma.com/events/'},
 {title:'Cape Cod Doxie Day',date:'2026-09-26',region:'Cape + Islands',city:'Barnstable',venue:'Barnstable',category:'Fair & Festival',free:false,featured:true,source:'https://www.visitma.com/events/'},
 {title:'Yarmouth Seaside Festival',date:'2026-10-10',end:'2026-10-12',region:'Cape + Islands',city:'South Yarmouth',venue:'South Yarmouth',category:'Fair & Festival',free:false,featured:true,source:'https://www.visitma.com/events/'},
 {title:"A Night at the Museum Gala",date:'2026-10-03',region:'Central Mass',city:'Worcester',venue:'Worcester',category:'Arts & Culture',free:false,featured:false,source:'https://www.visitma.com/events/'},
 {title:'Weekend of Wonder',date:'2026-10-10',end:'2026-10-12',region:'Central Mass',city:'Boylston',venue:'New England Botanic Garden',category:'Family',free:false,featured:true,source:'https://www.visitma.com/events/'},
 {title:'The 167th Belchertown Fair',date:'2026-09-25',end:'2026-09-27',region:'Western Mass + Berkshires',city:'Belchertown',venue:'Belchertown',category:'Fair & Festival',free:false,featured:true,source:'https://www.visitma.com/events/'},
 {title:'Housatonic Heritage Walk',date:'2026-09-26',region:'Western Mass + Berkshires',city:'Stockbridge',venue:'Stockbridge',category:'Outdoor',free:true,featured:true,source:'https://www.visitma.com/events/'}
];
const search=document.getElementById('search'), regionFilter=document.getElementById('regionFilter'), categoryFilter=document.getElementById('categoryFilter'), list=document.getElementById('eventList'), count=document.getElementById('eventCount');
let quick='all'; let viewDate=new Date(2026,8,1);
function fmtDate(d){return new Date(d+'T12:00:00')}
function renderCalendar(){const y=viewDate.getFullYear(),m=viewDate.getMonth();document.getElementById('monthLabel').textContent=viewDate.toLocaleDateString('en-US',{month:'long',year:'numeric'});const grid=document.getElementById('monthGrid');grid.innerHTML='';['SUN','MON','TUE','WED','THU','FRI','SAT'].forEach(x=>grid.insertAdjacentHTML('beforeend',`<div class="dow">${x}</div>`));const first=new Date(y,m,1).getDay(),days=new Date(y,m+1,0).getDate();for(let i=0;i<first;i++)grid.insertAdjacentHTML('beforeend','<div class="day blank"></div>');for(let d=1;d<=days;d++){const cur=new Date(y,m,d), has=events.some(e=>{const s=fmtDate(e.date), en=fmtDate(e.end||e.date);return cur>=s&&cur<=en});grid.insertAdjacentHTML('beforeend',`<div class="day ${has?'has-event':''}">${d}</div>`)}}
function matchesQuick(e){const today=new Date('2026-09-21T12:00:00');const d=fmtDate(e.date);if(quick==='free')return e.free;if(quick==='featured')return e.featured;if(quick==='week')return d>=today&&d<=new Date('2026-09-27T23:59:59');if(quick==='weekend')return d>=new Date('2026-09-25T00:00:00')&&d<=new Date('2026-09-27T23:59:59');return true}
function renderEvents(){const q=search.value.toLowerCase().trim(), reg=regionFilter.value, cat=categoryFilter.value;const filtered=events.filter(e=>(reg==='all'||e.region===reg)&&(cat==='all'||e.category===cat)&&matchesQuick(e)&&(!q||`${e.title} ${e.city} ${e.venue} ${e.region}`.toLowerCase().includes(q))).sort((a,b)=>a.date.localeCompare(b.date));count.textContent=`${filtered.length} shown`;list.innerHTML=filtered.map(e=>{const d=fmtDate(e.date);return `<article class="event-card"><div class="date-tile"><span>${d.toLocaleDateString('en-US',{month:'short'}).toUpperCase()}</span><strong>${d.getDate()}</strong></div><div><h3>${e.title}</h3><div class="event-meta">${e.city}, MA • ${e.region} • ${e.venue}${e.end?` • through ${fmtDate(e.end).toLocaleDateString('en-US',{month:'short',day:'numeric'})}`:''}</div><div style="margin-top:7px"><a href="${e.source}" target="_blank" rel="noreferrer">Official/source listing ↗</a></div></div><span class="event-badge">${e.free?'FREE • ':''}${e.category}</span></article>`}).join('')||'<p class="muted">No events match those filters.</p>'}
[search,regionFilter,categoryFilter].forEach(el=>el.addEventListener('input',renderEvents));document.querySelectorAll('.chip[data-filter]').forEach(btn=>btn.addEventListener('click',()=>{document.querySelectorAll('.chip[data-filter]').forEach(x=>x.classList.remove('active'));btn.classList.add('active');quick=btn.dataset.filter;renderEvents()}));document.getElementById('resetBtn').onclick=()=>{search.value='';regionFilter.value='all';categoryFilter.value='all';quick='all';document.querySelectorAll('.chip[data-filter]').forEach(x=>x.classList.toggle('active',x.dataset.filter==='all'));renderEvents()};document.getElementById('prevMonth').onclick=()=>{viewDate=new Date(viewDate.getFullYear(),viewDate.getMonth()-1,1);renderCalendar()};document.getElementById('nextMonth').onclick=()=>{viewDate=new Date(viewDate.getFullYear(),viewDate.getMonth()+1,1);renderCalendar()};renderCalendar();renderEvents();
